.TH octocatalog-diff "1" "January 2017" "octocatalog-diff" "User Commands"
.SH NAME
\fBoctocatalog-diff\fP \- Compile and compare Puppet catalogs

.SH SYNOPSIS
octocatalog-diff [options]

.SH DESCRIPTION
\fBoctocatalog-diff\fP is a tool to detect and display differences in Puppet
catalogs compiled from different environments. The catalogs may be
obtained through any of the following means:

.RS
.IP \[bu]
Compilation using a local puppet instance
.IP \[bu]
Puppet master 3.x/4.x HTTP API
.IP \[bu]
PuppetDB HTTP API
.IP \[bu]
Precompiled JSON catalogs
.RE

\fBoctocatalog-diff\fP filters out attributes or resources with no effect
(e.g. tags) and displays only state differences between the two
catalogs. It does not require a working Puppet master (or puppetserver),
making it suitable for development use and use in Continuous Integration
environments.

.SH USAGE

For a list of all  available options, please consult the output of
\fBoctocatalog-diff --help\fP.  Usage examples are available under
/usr/share/doc/octocatalog-diff.

.SH "SEE ALSO"
.BR puppet (8)

.SH AUTHOR
\fBoctocatalog-diff\fP was originally written by GitHub Inc.

This manual page was written by Apollon Oikonomopoulos <apoikos@debian.org> for
the Debian project (but may be used by others).
